#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : presentproto
Version  : 1.0
Release  : 7
URL      : http://xorg.freedesktop.org/releases/individual/proto/presentproto-1.0.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/proto/presentproto-1.0.tar.gz
Summary  : Present extension headers
Group    : Development/Tools
License  : HPND
Requires: presentproto-doc
BuildRequires : pkgconfig(xorg-macros)

%description
No detailed description available

%package dev
Summary: dev components for the presentproto package.
Group: Development
Provides: presentproto-devel

%description dev
dev components for the presentproto package.


%package doc
Summary: doc components for the presentproto package.
Group: Documentation

%description doc
doc components for the presentproto package.


%prep
%setup -q -n presentproto-1.0

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/presentproto.h
/usr/include/X11/extensions/presenttokens.h
/usr/lib64/pkgconfig/presentproto.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/presentproto/*
