#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x9DB0235556F8CFAD (jcristau@debian.org)
#
Name     : presentproto
Version  : 1.1
Release  : 11
URL      : http://xorg.freedesktop.org/releases/individual/proto/presentproto-1.1.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/proto/presentproto-1.1.tar.gz
Source99 : http://xorg.freedesktop.org/releases/individual/proto/presentproto-1.1.tar.gz.sig
Summary  : Present extension headers
Group    : Development/Tools
License  : HPND MIT
Requires: presentproto-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(xorg-macros)

%description
The Present Extension
The Present extension provides a way for applications to update their
window contents from a pixmap in a well defined fashion, synchronizing
with the display refresh and potentially using a more efficient
mechanism than copying the contents of the source pixmap.

%package dev
Summary: dev components for the presentproto package.
Group: Development
Provides: presentproto-devel

%description dev
dev components for the presentproto package.


%package dev32
Summary: dev32 components for the presentproto package.
Group: Default
Requires: presentproto-dev

%description dev32
dev32 components for the presentproto package.


%package doc
Summary: doc components for the presentproto package.
Group: Documentation

%description doc
doc components for the presentproto package.


%prep
%setup -q -n presentproto-1.1
pushd ..
cp -a presentproto-1.1 build32
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1485529430
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1485529430
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/presentproto.h
/usr/include/X11/extensions/presenttokens.h
/usr/lib64/pkgconfig/presentproto.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/pkgconfig/32presentproto.pc
/usr/lib32/pkgconfig/presentproto.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/presentproto/*
